version: "3"
services:
  fe:
    image: apache-doris-fe:2.1.5
    container_name: doris_fe
    hostname: fe
    environment:
     - FE_SERVERS=fe1:<doris-fe-internal-ip>:9010
     - FE_ID=1
    ports:
      - 9031:8030
      - 9030:9030

    volumes:
     - ./data/doris/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
     - ./data/doris/fe/log/:/opt/apache-doris/fe/log/
     - ./data/doris/fe/conf/:/opt/apache-doris/fe/conf/
    networks:
       doris_net:
         ipv4_address: <doris-fe-internal-ip>


         
  be:
    image: apache-doris-be:2.1.5
    hostname: be
    container_name: doris_be
    environment:
     - FE_SERVERS=fe1:<doris-fe-internal-ip>:9010
     - BE_ADDR=<doris-be-internal-ip>:9050
    ports:
     - 8040:8040
    volumes:
     - ./data/doris/be/storage/:/opt/apache-doris/be/storage/
     - ./data/doris/be/conf/:/opt/apache-doris/be/conf/
     - ./data/doris/be/log/:/opt/apache-doris/be/log/
     - ./data/doris/be/script/:/docker-entrypoint-initdb.d/
    depends_on:
      - fe
    networks:
       doris_net:
         ipv4_address: <doris-be-internal-ip>


networks:
   doris_net:
     ipam:
       config:
         - subnet: <docker-subnet>/16