CREATE STORAGE VAULT IF NOT EXISTS ssb_s3_vault
    PROPERTIES (
        "type"="S3",                                            -- required
        "s3.endpoint" = "http://10.136.218.207:9001",          -- required
        "s3.external_endpoint" = "http://10.136.218.207:9001", -- required
        "s3.bucket" = "dataplatform",                     -- required
        "s3.region" = "us-east-1",                                     -- required
        "s3.root.path" = "dataplatform/doris",                     -- required
        "s3.access_key" = "Mivcp6lLE8G5R0bfFMZV",                                 -- required
        "s3.secret_key" = "Bhb2CGpDHuACuqBwKCC1FtA4yDeCdscwBxTQcdTn",                                 -- required
        "provider" = "s3",                                     -- required
    );



    ###########################
CREATE RESOURCE "remote_s3"
PROPERTIES
(
    "type" = "s3",
    "s3.endpoint" = "bj.s3.com",
    "s3.region" = "bj",
    "s3.bucket" = "test-bucket",
    "s3.root.path" = "path/to/root",
    "s3.access_key" = "bbb",
    "s3.secret_key" = "aaaa",
    "s3.connection.maximum" = "50",
    "s3.connection.request.timeout" = "3000",
    "s3.connection.timeout" = "1000",
    "use_path_style" = "true"
);